export enum ERROR_CODES {
  // Authentication Errors
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  TOKEN_REQUIRED = "TOKEN_REQUIRED",
  INVALID_TOKEN = "INVALID_TOKEN",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  INVALID_GOOGLE_TOKEN = "INVALID_GOOGLE_TOKEN",
  AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED",
  AUTHENTICATION_SERVICE_ERROR = "AUTHENTICATION_SERVICE_ERROR",
  INVALID_TOKEN_PURPOSE = "INVALID_TOKEN_PURPOSE",
  TOKEN_VERIFICATION_FAILED = "TOKEN_VERIFICATION_FAILED",

  // User Errors
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_EMAIL_ALREADY_EXISTS = "USER_EMAIL_ALREADY_EXISTS",
  UNAUTHORIZED_USER_UPDATE = "UNAUTHORIZED_USER_UPDATE",
  USERS_CAN_ONLY_ACCESS_OWN_DATA = "USERS_CAN_ONLY_ACCESS_OWN_DATA",

  // Account Status Errors
  EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
  ACCOUNT_BLOCKED = "ACCOUNT_BLOCKED",
  EMAIL_CONFIRMATION_FAILED = "EMAIL_CONFIRMATION_FAILED",

  // OTP Errors
  OTP_NOT_FOUND = "OTP_NOT_FOUND",
  OTP_EXPIRED = "OTP_EXPIRED",
  INVALID_OTP = "INVALID_OTP",
  OTP_REQUEST_NOT_FOUND = "OTP_REQUEST_NOT_FOUND",

  // Device Errors
  DEVICE_NOT_FOUND = "DEVICE_NOT_FOUND",
  UNAUTHORIZED_DEVICE_REMOVAL = "UNAUTHORIZED_DEVICE_REMOVAL",

  // Permission/Authorization Errors
  NO_TOKEN_PROVIDED = "NO_TOKEN_PROVIDED",
  INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS",
  ADMIN_ONLY = "ADMIN_ONLY",
  UNAUTHORIZED_PERSONAL_INFO_UPDATE = "UNAUTHORIZED_PERSONAL_INFO_UPDATE",
  UNAUTHORIZED_ADDRESS_UPDATE = "UNAUTHORIZED_ADDRESS_UPDATE",
  UNAUTHORIZED_STATUS_VIEW = "UNAUTHORIZED_STATUS_VIEW",

  // Password/Reset Errors
  INVALID_RESET_TOKEN = "INVALID_RESET_TOKEN",
  PASSWORD_RESET_FAILED = "PASSWORD_RESET_FAILED",

  // OAuth Errors
  OAUTH_CODE_VERIFIER_NOT_FOUND = "OAUTH_CODE_VERIFIER_NOT_FOUND",
  OAUTH_PROFILE_FETCH_FAILED = "OAUTH_PROFILE_FETCH_FAILED",

  // External Service Errors
  LISTMONK_SUBSCRIPTION_FAILED = "LISTMONK_SUBSCRIPTION_FAILED",

  // Configuration Errors
  INVALID_TIME_UNIT = "INVALID_TIME_UNIT",
  INVALID_CONFIRMATION_TOKEN = "INVALID_CONFIRMATION_TOKEN",
  INVALID_TOKEN_TYPE = "INVALID_TOKEN_TYPE",
  GENERATE_CONFIRMATION_TOKEN_FAILED = "GENERATE_CONFIRMATION_TOKEN_FAILED",

  // Rate Limiting
  OTP_RATE_LIMIT_EXCEEDED = "OTP_RATE_LIMIT_EXCEEDED",

  // Update Operation Errors
  UPDATE_PERSONAL_INFO_FAILED = "UPDATE_PERSONAL_INFO_FAILED",
  UPDATE_ADDRESS_FAILED = "UPDATE_ADDRESS_FAILED",
  GET_USER_STATUS_FAILED = "GET_USER_STATUS_FAILED",

  // Validation Errors
  VALIDATION_FAILED = "VALIDATION_FAILED",
}
