/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LandingHomeRouteImport } from './routes/landing/home'
import { Route as AuthCreateAccountRouteImport } from './routes/auth/create-account'

const AuthLazyRouteImport = createFileRoute('/auth')()
const LandingSimulatorLazyRouteImport = createFileRoute('/landing/simulator')()
const LandingProductLazyRouteImport = createFileRoute('/landing/product')()
const AuthThreeStepsLazyRouteImport = createFileRoute('/auth/three-steps')()

const AuthLazyRoute = AuthLazyRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/auth.lazy').then((d) => d.Route))
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingSimulatorLazyRoute = LandingSimulatorLazyRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => LandingRoute,
} as any).lazy(() =>
  import('./routes/landing/simulator.lazy').then((d) => d.Route),
)
const LandingProductLazyRoute = LandingProductLazyRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => LandingRoute,
} as any).lazy(() =>
  import('./routes/landing/product.lazy').then((d) => d.Route),
)
const AuthThreeStepsLazyRoute = AuthThreeStepsLazyRouteImport.update({
  id: '/three-steps',
  path: '/three-steps',
  getParentRoute: () => AuthLazyRoute,
} as any).lazy(() =>
  import('./routes/auth/three-steps.lazy').then((d) => d.Route),
)
const LandingHomeRoute = LandingHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LandingRoute,
} as any)
const AuthCreateAccountRoute = AuthCreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => AuthLazyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/landing': typeof LandingRouteWithChildren
  '/auth': typeof AuthLazyRouteWithChildren
  '/auth/create-account': typeof AuthCreateAccountRoute
  '/landing/home': typeof LandingHomeRoute
  '/auth/three-steps': typeof AuthThreeStepsLazyRoute
  '/landing/product': typeof LandingProductLazyRoute
  '/landing/simulator': typeof LandingSimulatorLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/landing': typeof LandingRouteWithChildren
  '/auth': typeof AuthLazyRouteWithChildren
  '/auth/create-account': typeof AuthCreateAccountRoute
  '/landing/home': typeof LandingHomeRoute
  '/auth/three-steps': typeof AuthThreeStepsLazyRoute
  '/landing/product': typeof LandingProductLazyRoute
  '/landing/simulator': typeof LandingSimulatorLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/landing': typeof LandingRouteWithChildren
  '/auth': typeof AuthLazyRouteWithChildren
  '/auth/create-account': typeof AuthCreateAccountRoute
  '/landing/home': typeof LandingHomeRoute
  '/auth/three-steps': typeof AuthThreeStepsLazyRoute
  '/landing/product': typeof LandingProductLazyRoute
  '/landing/simulator': typeof LandingSimulatorLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/landing'
    | '/auth'
    | '/auth/create-account'
    | '/landing/home'
    | '/auth/three-steps'
    | '/landing/product'
    | '/landing/simulator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/landing'
    | '/auth'
    | '/auth/create-account'
    | '/landing/home'
    | '/auth/three-steps'
    | '/landing/product'
    | '/landing/simulator'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/landing'
    | '/auth'
    | '/auth/create-account'
    | '/landing/home'
    | '/auth/three-steps'
    | '/landing/product'
    | '/landing/simulator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  LandingRoute: typeof LandingRouteWithChildren
  AuthLazyRoute: typeof AuthLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/simulator': {
      id: '/landing/simulator'
      path: '/simulator'
      fullPath: '/landing/simulator'
      preLoaderRoute: typeof LandingSimulatorLazyRouteImport
      parentRoute: typeof LandingRoute
    }
    '/landing/product': {
      id: '/landing/product'
      path: '/product'
      fullPath: '/landing/product'
      preLoaderRoute: typeof LandingProductLazyRouteImport
      parentRoute: typeof LandingRoute
    }
    '/auth/three-steps': {
      id: '/auth/three-steps'
      path: '/three-steps'
      fullPath: '/auth/three-steps'
      preLoaderRoute: typeof AuthThreeStepsLazyRouteImport
      parentRoute: typeof AuthLazyRoute
    }
    '/landing/home': {
      id: '/landing/home'
      path: '/home'
      fullPath: '/landing/home'
      preLoaderRoute: typeof LandingHomeRouteImport
      parentRoute: typeof LandingRoute
    }
    '/auth/create-account': {
      id: '/auth/create-account'
      path: '/create-account'
      fullPath: '/auth/create-account'
      preLoaderRoute: typeof AuthCreateAccountRouteImport
      parentRoute: typeof AuthLazyRoute
    }
  }
}

interface LandingRouteChildren {
  LandingHomeRoute: typeof LandingHomeRoute
  LandingProductLazyRoute: typeof LandingProductLazyRoute
  LandingSimulatorLazyRoute: typeof LandingSimulatorLazyRoute
}

const LandingRouteChildren: LandingRouteChildren = {
  LandingHomeRoute: LandingHomeRoute,
  LandingProductLazyRoute: LandingProductLazyRoute,
  LandingSimulatorLazyRoute: LandingSimulatorLazyRoute,
}

const LandingRouteWithChildren =
  LandingRoute._addFileChildren(LandingRouteChildren)

interface AuthLazyRouteChildren {
  AuthCreateAccountRoute: typeof AuthCreateAccountRoute
  AuthThreeStepsLazyRoute: typeof AuthThreeStepsLazyRoute
}

const AuthLazyRouteChildren: AuthLazyRouteChildren = {
  AuthCreateAccountRoute: AuthCreateAccountRoute,
  AuthThreeStepsLazyRoute: AuthThreeStepsLazyRoute,
}

const AuthLazyRouteWithChildren = AuthLazyRoute._addFileChildren(
  AuthLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  LandingRoute: LandingRouteWithChildren,
  AuthLazyRoute: AuthLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
