/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LandingHomeRouteImport } from './routes/landing/home'

const LandingSimulatorLazyRouteImport = createFileRoute('/landing/simulator')()
const LandingProductLazyRouteImport = createFileRoute('/landing/product')()
const LandingLegalTermsLazyRouteImport = createFileRoute(
  '/landing/_legal/terms',
)()
const LandingLegalPrivacyPolicyLazyRouteImport = createFileRoute(
  '/landing/_legal/privacy-policy',
)()
const LandingLegalCommercialsLazyRouteImport = createFileRoute(
  '/landing/_legal/commercials',
)()

const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingSimulatorLazyRoute = LandingSimulatorLazyRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => LandingRoute,
} as any).lazy(() =>
  import('./routes/landing/simulator.lazy').then((d) => d.Route),
)
const LandingProductLazyRoute = LandingProductLazyRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => LandingRoute,
} as any).lazy(() =>
  import('./routes/landing/product.lazy').then((d) => d.Route),
)
const LandingHomeRoute = LandingHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LandingRoute,
} as any)
const LandingLegalTermsLazyRoute = LandingLegalTermsLazyRouteImport.update({
  id: '/_legal/terms',
  path: '/terms',
  getParentRoute: () => LandingRoute,
} as any).lazy(() =>
  import('./routes/landing/_legal/terms.lazy').then((d) => d.Route),
)
const LandingLegalPrivacyPolicyLazyRoute =
  LandingLegalPrivacyPolicyLazyRouteImport.update({
    id: '/_legal/privacy-policy',
    path: '/privacy-policy',
    getParentRoute: () => LandingRoute,
  } as any).lazy(() =>
    import('./routes/landing/_legal/privacy-policy.lazy').then((d) => d.Route),
  )
const LandingLegalCommercialsLazyRoute =
  LandingLegalCommercialsLazyRouteImport.update({
    id: '/_legal/commercials',
    path: '/commercials',
    getParentRoute: () => LandingRoute,
  } as any).lazy(() =>
    import('./routes/landing/_legal/commercials.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/landing': typeof LandingRouteWithChildren
  '/landing/home': typeof LandingHomeRoute
  '/landing/product': typeof LandingProductLazyRoute
  '/landing/simulator': typeof LandingSimulatorLazyRoute
  '/landing/commercials': typeof LandingLegalCommercialsLazyRoute
  '/landing/privacy-policy': typeof LandingLegalPrivacyPolicyLazyRoute
  '/landing/terms': typeof LandingLegalTermsLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/landing': typeof LandingRouteWithChildren
  '/landing/home': typeof LandingHomeRoute
  '/landing/product': typeof LandingProductLazyRoute
  '/landing/simulator': typeof LandingSimulatorLazyRoute
  '/landing/commercials': typeof LandingLegalCommercialsLazyRoute
  '/landing/privacy-policy': typeof LandingLegalPrivacyPolicyLazyRoute
  '/landing/terms': typeof LandingLegalTermsLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/landing': typeof LandingRouteWithChildren
  '/landing/home': typeof LandingHomeRoute
  '/landing/product': typeof LandingProductLazyRoute
  '/landing/simulator': typeof LandingSimulatorLazyRoute
  '/landing/_legal/commercials': typeof LandingLegalCommercialsLazyRoute
  '/landing/_legal/privacy-policy': typeof LandingLegalPrivacyPolicyLazyRoute
  '/landing/_legal/terms': typeof LandingLegalTermsLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/landing'
    | '/landing/home'
    | '/landing/product'
    | '/landing/simulator'
    | '/landing/commercials'
    | '/landing/privacy-policy'
    | '/landing/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/landing'
    | '/landing/home'
    | '/landing/product'
    | '/landing/simulator'
    | '/landing/commercials'
    | '/landing/privacy-policy'
    | '/landing/terms'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/landing'
    | '/landing/home'
    | '/landing/product'
    | '/landing/simulator'
    | '/landing/_legal/commercials'
    | '/landing/_legal/privacy-policy'
    | '/landing/_legal/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  LandingRoute: typeof LandingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/simulator': {
      id: '/landing/simulator'
      path: '/simulator'
      fullPath: '/landing/simulator'
      preLoaderRoute: typeof LandingSimulatorLazyRouteImport
      parentRoute: typeof LandingRoute
    }
    '/landing/product': {
      id: '/landing/product'
      path: '/product'
      fullPath: '/landing/product'
      preLoaderRoute: typeof LandingProductLazyRouteImport
      parentRoute: typeof LandingRoute
    }
    '/landing/home': {
      id: '/landing/home'
      path: '/home'
      fullPath: '/landing/home'
      preLoaderRoute: typeof LandingHomeRouteImport
      parentRoute: typeof LandingRoute
    }
    '/landing/_legal/terms': {
      id: '/landing/_legal/terms'
      path: '/terms'
      fullPath: '/landing/terms'
      preLoaderRoute: typeof LandingLegalTermsLazyRouteImport
      parentRoute: typeof LandingRoute
    }
    '/landing/_legal/privacy-policy': {
      id: '/landing/_legal/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/landing/privacy-policy'
      preLoaderRoute: typeof LandingLegalPrivacyPolicyLazyRouteImport
      parentRoute: typeof LandingRoute
    }
    '/landing/_legal/commercials': {
      id: '/landing/_legal/commercials'
      path: '/commercials'
      fullPath: '/landing/commercials'
      preLoaderRoute: typeof LandingLegalCommercialsLazyRouteImport
      parentRoute: typeof LandingRoute
    }
  }
}

interface LandingRouteChildren {
  LandingHomeRoute: typeof LandingHomeRoute
  LandingProductLazyRoute: typeof LandingProductLazyRoute
  LandingSimulatorLazyRoute: typeof LandingSimulatorLazyRoute
  LandingLegalCommercialsLazyRoute: typeof LandingLegalCommercialsLazyRoute
  LandingLegalPrivacyPolicyLazyRoute: typeof LandingLegalPrivacyPolicyLazyRoute
  LandingLegalTermsLazyRoute: typeof LandingLegalTermsLazyRoute
}

const LandingRouteChildren: LandingRouteChildren = {
  LandingHomeRoute: LandingHomeRoute,
  LandingProductLazyRoute: LandingProductLazyRoute,
  LandingSimulatorLazyRoute: LandingSimulatorLazyRoute,
  LandingLegalCommercialsLazyRoute: LandingLegalCommercialsLazyRoute,
  LandingLegalPrivacyPolicyLazyRoute: LandingLegalPrivacyPolicyLazyRoute,
  LandingLegalTermsLazyRoute: LandingLegalTermsLazyRoute,
}

const LandingRouteWithChildren =
  LandingRoute._addFileChildren(LandingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  LandingRoute: LandingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
